import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Landing from "@components/Landing";
import Main from "@components/Main";
import withTransition from "@components/withTransition";
import { useAccount } from "wagmi";

const Home: NextPage = () => {
  const { address } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>PayPod: Web3 Gaming Payment Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{!address ? <Landing /> : <Main />}</main>
    </div>
  );
};

export default withTransition(Home);
